// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABtCAl14pGcpCSyc5TH-GWZI1nv0xL3CY',
    appId: '1:670626624001:web:84863644057358f4154600',
    messagingSenderId: '670626624001',
    projectId: 'inhouston-209c0',
    authDomain: 'inhouston-209c0.firebaseapp.com',
    storageBucket: 'inhouston-209c0.appspot.com',
    measurementId: 'G-ESSRXLSPZQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeHXJu64cXyt2l2jUM5M5UGyiwewENffU',
    appId: '1:670626624001:ios:dd0368f8404514be154600',
    messagingSenderId: '670626624001',
    projectId: 'inhouston-209c0',
    storageBucket: 'inhouston-209c0.appspot.com',
    iosBundleId: 'com.inhouston.servicios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeHXJu64cXyt2l2jUM5M5UGyiwewENffU',
    appId: '1:670626624001:ios:424810cd6ab8fc5d154600',
    messagingSenderId: '670626624001',
    projectId: 'inhouston-209c0',
    storageBucket: 'inhouston-209c0.appspot.com',
    iosBundleId: 'com.example.inhouston',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABtCAl14pGcpCSyc5TH-GWZI1nv0xL3CY',
    appId: '1:670626624001:web:b57f11d023037a4b154600',
    messagingSenderId: '670626624001',
    projectId: 'inhouston-209c0',
    authDomain: 'inhouston-209c0.firebaseapp.com',
    storageBucket: 'inhouston-209c0.appspot.com',
    measurementId: 'G-S3D2FXBVGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqP3HGDfU3EHCK3PfN6Ac-5wMItcxYxkI',
    appId: '1:670626624001:android:2a2fa88a45ada696154600',
    messagingSenderId: '670626624001',
    projectId: 'inhouston-209c0',
    storageBucket: 'inhouston-209c0.appspot.com',
  );

}